import { useEffect, useRef, useState } from 'react'
import { motion, useScroll, useTransform } from 'framer-motion'
import Lenis from 'lenis'
import { ArrowUpRight, Check, Clock, Shield, BadgeCheck, Gauge, Zap, Code2 } from 'lucide-react'

function useSmoothScroll() {
  useEffect(() => { const lenis = new Lenis({ duration: 1.2, smoothWheel: true }); function loop(t) { lenis.raf(t * 1000); requestAnimationFrame(loop) } requestAnimationFrame(loop); if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) lenis.stop(); return () => lenis.destroy() }, [])
}
const SplitWords = ({ text, className = '' }) => { const ref = useRef(null); const { scrollYProgress } = useScroll({ target: ref, offset: ['start 88%', 'end 60%'] }); const words = text.split(' '); const ys = words.map((w, i) => useTransform(scrollYProgress, [i / words.length, (i + 1.2) / words.length], ['115%', '0%'], { clamp: true })); return <h2 ref={ref} className={className} style={{ margin: 0 }}>{words.map((w, i) => <span key={i} className="wm" style={{ display: 'inline-block', overflow: 'hidden', paddingBottom: '.1em' }} aria-hidden="true"><motion.span style={{ y: ys[i], display: 'inline-block' }}>{w}</motion.span>{'\u00A0'}</span>)}</h2> }
const Reveal = ({ children, delay = 0 }) => { const ref = useRef(null); const { scrollYProgress } = useScroll({ target: ref, offset: ['start 88%', 'end 65%'] }); const y = useTransform(scrollYProgress, [0, 1], [48, 0]); const o = useTransform(scrollYProgress, [0, .35], [0, 1]); return <motion.div ref={ref} style={{ y, opacity: o }}>{children}</motion.div> }
const Magnetic = ({ children, strength = .3 }) => { const ref = useRef(null); return <motion.div ref={ref} onMouseMove={(e) => { const el = ref.current, r = el.getBoundingClientRect(); el.style.transform = `translate(${(e.clientX - (r.left + r.width / 2)) * strength}px, ${(e.clientY - (r.top + r.height / 2)) * strength}px)` }} onMouseLeave={() => { ref.current.style.transform = 'translate(0,0)' }} style={{ transition: 'transform .4s cubic-bezier(.22,1,.36,1)', display: 'inline-block' }}>{children}</motion.div> }

const Header = () => <header className="site-header"><div className="header-inner"><a href="#" className="logo">Sideway<span>.</span></a><nav><a href="#rail">The rail</a><a href="#pricing">Pricing</a><a href="#process">Process</a><Magnetic><motion.a href="#contact" whileHover={{ scale: 1.05 }} className="btn-cta">Start a project</motion.a></Magnetic></nav></div></header>
const Hero = () => { const ref = useRef(null); const { scrollYProgress } = useScroll({ target: ref, offset: ['start start', 'end start'] }); const y = useTransform(scrollYProgress, [0, 1], ['0%', '20%']); const o = useTransform(scrollYProgress, [0, .5], [1, 0]); return <section ref={ref} className="hero"><motion.div className="hero-inner" style={{ y, opacity: o }}><p className="kicker">Horizontal storytelling — scroll down, go sideways</p><h1><motion.span className="hw" initial={{ opacity: 0, y: 90 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .8, ease: [0.16,1,0.3,1], delay: .3 }}>Keep</motion.span> <motion.span className="hw accent" initial={{ opacity: 0, y: 90 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .8, ease: [0.16,1,0.3,1], delay: .42 }}>scrolling.</motion.span></h1><motion.p className="hero-sub" initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .75 }}>Pinned, scroll-driven horizontal rails — the signature move of award-winning studios. Vertical scroll, sideways story.</motion.p><motion.div className="hero-ctas" initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .9 }}><Magnetic><motion.a href="#rail" whileHover={{ scale: 1.06 }} className="btn-primary">Experience the rail <ArrowUpRight size={16} style={{ verticalAlign: 'middle', marginLeft: 4 }} /></motion.a></Magnetic><Magnetic><motion.a href="#pricing" whileHover={{ scale: 1.06 }} className="btn-ghost">See pricing</motion.a></Magnetic></motion.div></motion.div></section> }

const Rail = () => {
  const ref = useRef(null)
  const { scrollYProgress } = useScroll({ target: ref, offset: ['start start', 'end end'] })
  const items = [
    { n: '01', t: 'Brand timelines', d: 'A brand story told as one sweeping journey.' },
    { n: '02', t: 'Product galleries', d: 'Let visitors swipe through your range sideways.' },
    { n: '03', t: 'Service rows', d: 'All offerings in one scannable sideways glance.' },
    { n: '04', t: 'Roadmaps', d: 'A product roadmap that travels horizontally.' },
    { n: '05', t: 'Portfolios', d: 'Work that reads left-to-right, not top-to-bottom.' },
  ]
  const x = useTransform(scrollYProgress, [0, 1], ['2%', '-80%'])
  return (
    <section ref={ref} className="hwrap" id="rail"><div className="hpin"><div className="hrail" style={{ x }}>
      {items.map((it, i) => <motion.div key={i} className="hi" whileHover={{ y: -8 }}><div className="num">{it.n}</div><div><h3>{it.t}</h3><p>{it.d}</p></div></motion.div>)}
    </div></div></section>
  )
}
const Stack = () => { const stack = ['GSAP', 'ScrollTrigger', 'React', 'framer-motion', 'lenis', 'TypeScript', 'Vite']; const metrics = [{ icon: <Gauge size={18} />, n: '60fps', l: 'Pin motion' }, { icon: <Zap size={18} />, n: '1.0s', l: 'Avg load' }, { icon: <Code2 size={18} />, n: '100', l: 'Core Web Vitals' }, { icon: <BadgeCheck size={18} />, n: 'AA', l: 'Accessible' }]; return <section className="stackband"><div className="wrap"><Reveal><p className="stack-label">Pinned rail, performance-first</p></Reveal><Reveal delay={.08}><div className="stack-row">{stack.map(s => <span key={s}>{s}</span>)}</div></Reveal><div className="tech-grid">{metrics.map((m, i) => <Reveal key={i} delay={i * .06}><div className="tech-metric">{m.icon}<div><b>{m.n}</b><span>{m.l}</span></div></div></Reveal>)}</div></div></section> }
const RESULTS = [{ n: '+160%', l: 'Time-on-page', tag: 'sideways keeps them swiping' }, { n: '+30%', l: 'Conversion', tag: 'guided, cinematic journeys' }, { n: '35+', l: 'Rails shipped', tag: 'global launches' }, { n: '0', l: 'Jank on scroll', tag: '60fps pinned' }]
const Results = () => <section className="results" id="results"><div className="wrap"><Reveal><SplitWords text="Sideways stories convert." className="sec-title" /></Reveal><p className="sec-sub">A pinned horizontal rail turns a scroll into a directed experience — and directed people convert.</p><div className="results-grid">{RESULTS.map((r, i) => <Reveal key={i} delay={i * .08}><div className="result-card"><div className="result-n">{r.n}</div><div className="result-l">{r.l}</div><div className="result-tag">{r.tag}</div></div></Reveal>)}</div></div></section>
const SERVICES = [{ icon: '01', title: 'Timeline rails', desc: 'History and milestones as a horizontal journey.', price: 'from €2,900', time: '2-3 wks' }, { icon: '02', title: 'Product galleries', desc: 'Swipe-able product ranges in a single motion.', price: 'from €3,400', time: '3 wks' }, { icon: '03', title: 'Service showcases', desc: 'Every offering in one sweeping, scannable glance.', price: 'from €3,800', time: '3 wks' }, { icon: '04', title: 'Full rail sites', desc: 'Complete React builds built around a horizontal narrative.', price: 'from €5,200', time: '4-5 wks' }]
const Services = () => <section className="services" id="services"><div className="wrap"><Reveal><SplitWords text="What we build." className="sec-title" /></Reveal><div className="svc-grid">{SERVICES.map((s, i) => <Reveal key={i} delay={i * .08}><motion.div className="service-card" whileHover={{ y: -8, transition: { type: 'spring', stiffness: 300 } }}><div className="num">{s.icon}</div><h3>{s.title}</h3><p>{s.desc}</p><div className="svc-meta"><span className="price">{s.price}</span><span className="time"><Clock size={13} /> {s.time}</span></div><a href="#contact" className="svc-link">Start this →</a></motion.div></Reveal>)}</div></div></section>
const PLANS = [{ name: 'Rail', price: '€2,900', for: 'One horizontal rail', feats: ['1 pinned rail scene', '2 revision rounds', 'Optimised for speed', '2 week delivery'] }, { name: 'Journey', price: '€5,200', for: 'Full rail narrative site', feats: ['Multiple rails + scenes', 'Contact / CTA', '3 revision rounds', 'Performance report', '30 days support'] }, { name: 'Cinematic', price: '€9,000', for: 'Award-level journey', feats: ['Everything in Journey', 'Custom choreography', 'A/B ready', '90 days support'] }]
const Pricing = () => { const [sel, setSel] = useState(1); return <section className="pricing" id="pricing"><div className="wrap"><Reveal><SplitWords text="Clear pricing." className="sec-title" /></Reveal><div className="plan-grid">{PLANS.map((p, i) => <Reveal key={i} delay={i * .08}><motion.div className={`plan ${i === sel ? 'plan-feat' : ''}`} whileHover={{ y: -6 }} onClick={() => setSel(i)}>{i === sel && <span className="plan-pop">Most chosen</span>}<h3>{p.name}</h3><div className="plan-price">{p.price}</div><div className="plan-for">{p.for}</div><ul>{p.feats.map((f, k) => <li key={k}><Check size={15} /> {f}</li>)}</ul><motion.a href="#contact" className="plan-btn" whileHover={{ scale: 1.04 }}>Choose {p.name}</motion.a></motion.div></Reveal>)}</div><Reveal><div className="guarantee"><Shield size={18} /> Every rail ships with a <b>written delivery date</b> and <b>30-day support</b>.</div></Reveal></div></section> }
const PROCESS = [{ n: '01', t: 'Storyboard rail', d: 'We script the horizontal journey scene by scene.', icon: '📝' }, { n: '02', t: 'Design', d: 'Visual direction + a scrubbable prototype.', icon: '🎨' }, { n: '03', t: 'Build', d: 'GSAP pins + React dev in weekly sprints.', icon: '⚙️' }, { n: '04', t: 'Launch', d: 'Ship, measure scroll depth, improve.', icon: '📈' }]
const Process = () => <section className="process" id="process"><div className="wrap"><Reveal><SplitWords text="Built sideways, delivered on time." className="sec-title" /></Reveal><div className="proc-grid">{PROCESS.map((p, i) => <Reveal key={i} delay={i * .08}><motion.div className="proc-step" whileHover={{ y: -6 }}><div className="proc-num">{p.n}<span>{p.icon}</span></div><h4>{p.t}</h4><p>{p.d}</p></motion.div></Reveal>)}</div></div></section>
const QUOTES = [{ q: "Sideway's rail made our anniversary campaign unforgettable. Scroll depth +160%.", n: 'Rhea D.', r: 'CMO, Vantage' }, { q: "The sideways product gallery is genius. Visitors actually explore the range now.", n: 'Jonas F.', r: 'Founder, Northbeam' }, { q: "Delivered a cinematic rail on time — and it holds 60fps.", n: 'Lena M.', r: 'Brand lead, Alder' }]
const Testimonials = () => <section className="quotes"><div className="wrap"><Reveal><SplitWords text="Clients who kept swiping." className="sec-title" /></Reveal><div className="quotes-grid">{QUOTES.map((q, i) => <Reveal key={i} delay={i * .08}><figure className="quote"><div className="stars">★★★★★</div><blockquote>{q.q}</blockquote><figcaption><b>{q.n}</b><span>{q.r}</span></figcaption></figure></Reveal>)}</div></div></section>
const CTA = () => { const [sent, setSent] = useState(false); return <section className="cta" id="contact"><div className="wrap cta-inner"><Reveal><SplitWords text="Script your horizontal journey." className="sec-title" /></Reveal><p className="sec-sub">Tell us your story — a rail script, fixed quote and date within one business day.</p>{!sent ? <motion.form className="cta-form" initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} onSubmit={(e) => { e.preventDefault(); setSent(true) }}><div className="form-row"><input required placeholder="Your name" aria-label="Your name" /><input required type="email" placeholder="Work email" aria-label="Work email" /></div><textarea rows="3" placeholder="Tell us about the story you want told sideways" aria-label="Project details" /><Magnetic><motion.button whileHover={{ scale: 1.05 }} className="btn-primary" type="submit" style={{ border: 'none', cursor: 'pointer' }}>Send project brief <ArrowUpRight size={16} style={{ verticalAlign: 'middle', marginLeft: 4 }} /></motion.button></Magnetic><p className="form-note"><Shield size={13} /> Free quote · no obligation · reply within 1 business day</p></motion.form> : <motion.div className="cta-done" initial={{ scale: 0.8, opacity: 0 }} animate={{ scale: 1, opacity: 1 }}><BadgeCheck size={44} /><h3>Brief received 🎉</h3><p>We'll reply within one business day.</p></motion.div>}<div className="cta-contact"><span>Prefer email?</span> <a href="mailto:studio@sideway.studio">studio@sideway.studio</a></div></div></section> }
const Footer = () => <footer className="site-footer"><div className="wrap foot-inner"><span>© 2026 Sideway — horizontal storytelling.</span><span><a href="#rail">Rail</a> · <a href="#pricing">Pricing</a> · <a href="mailto:studio@sideway.studio">studio@sideway.studio</a></span></div></footer>

export default function App() {
  useSmoothScroll()
  return (<><Header /><Hero /><Rail /><Stack /><Results /><Services /><Pricing /><Process /><Testimonials /><CTA /><Footer /></>)
}
